<?php
    $servername = "localhost";
    $username = "pbtester";
    $password = "qkrrhkdrb1!";
    $dbname = "pbtester";

    $macro = array("{first_install.a_key}",
    "{first_install.a_cookie}",
    "{first_install.a_ip}",
    "{first_install.a_fp}",
    "{first_install.a_country}",
    "{first_install.a_city}",
    "{first_install.a_region}",
    "{first_install.a_appkey}",
    "{first_install.a_partner}",
    "{first_install.a_agency}",
    "{first_install.a_my_adgroup}",
    "{first_install.a_my_ad}",
    "{first_install.a_my_campaign}",
    "{first_install.a_adtouch_datetime}",
    "{first_install.a_adtouch_timestamp}",
    "{first_install.a_adtouch_timestamp_d}",
    "{first_install.m_creative}",
    "{first_install.m_publisher}",
    "{first_install.m_sub_publisher}",
    "{first_install.m_adgroup}",
    "{first_install.m_ad}",
    "{first_install.m_keyword}",
    "{first_install.m_placement}",
    "{first_install.m_cost_model}",
    "{first_install.m_cost}",
    "{first_install.m_cost_currency}",
    "{first_install.m_play_percent}",
    "{first_install.m_play_second}",
    "{first_install.m_view_percent}",
    "{first_install.m_view_second}",
    "{first_install.cb_1}",
    "{first_install.cb_2}",
    "{first_install.cb_3}",
    "{first_install.cb_4}",
    "{first_install.cb_5}",
    "{first_install.m_adid}",
    "{first_install.utm_source}",
    "{first_install.utm_medium}",
    "{first_install.utm_campaign}",
    "{first_install.utm_term}",
    "{first_install.utm_content}",
    "{first_install.adid}",
    "{first_install.is_attr_owner}",
    "{first_install.attr_model_flag}",
    "{first_install.attr_model_str}",
    "{first_install.i_request_type}",
    "{first_install.attribute_datetime}",
    "{first_install.attribute_timestamp}",
    "{first_install.attribute_timestamp_d}",
    "{first_install.seconds_gap}",
    "{first_install.deeplink_custom_path}",
    "{last_install.a_key}",
    "{last_install.a_cookie}",
    "{last_install.a_ip}",
    "{last_install.a_fp}",
    "{last_install.a_country}",
    "{last_install.a_city}",
    "{last_install.a_region}",
    "{last_install.a_appkey}",
    "{last_install.a_partner}",
    "{last_install.a_agency}",
    "{last_install.a_my_adgroup}",
    "{last_install.a_my_ad}",
    "{last_install.a_my_campaign}",
    "{last_install.a_adtouch_datetime}",
    "{last_install.a_adtouch_timestamp}",
    "{last_install.a_adtouch_timestamp_d}",
    "{last_install.m_creative}",
    "{last_install.m_publisher}",
    "{last_install.m_sub_publisher}",
    "{last_install.m_adgroup}",
    "{last_install.m_ad}",
    "{last_install.m_keyword}",
    "{last_install.m_placement}",
    "{last_install.m_cost_model}",
    "{last_install.m_cost}",
    "{last_install.m_cost_currency}",
    "{last_install.m_play_percent}",
    "{last_install.m_play_second}",
    "{last_install.m_view_percent}",
    "{last_install.m_view_second}",
    "{last_install.cb_1}",
    "{last_install.cb_2}",
    "{last_install.cb_3}",
    "{last_install.cb_4}",
    "{last_install.cb_5}",
    "{last_install.m_adid}",
    "{last_install.utm_source}",
    "{last_install.utm_medium}",
    "{last_install.utm_campaign}",
    "{last_install.utm_term}",
    "{last_install.utm_content}",
    "{last_install.adid}",
    "{last_install.is_attr_owner}",
    "{last_install.attr_model_flag}",
    "{last_install.attr_model_str}",
    "{last_install.i_request_type}",
    "{last_install.attribute_datetime}",
    "{last_install.attribute_timestamp}",
    "{last_install.attribute_timestamp_d}",
    "{last_install.seconds_gap}",
    "{last_install.deeplink_custom_path}",
    "{last_deeplink.a_key}",
    "{last_deeplink.a_cookie}",
    "{last_deeplink.a_ip}",
    "{last_deeplink.a_fp}",
    "{last_deeplink.a_country}",
    "{last_deeplink.a_city}",
    "{last_deeplink.a_region}",
    "{last_deeplink.a_appkey}",
    "{last_deeplink.a_partner}",
    "{last_deeplink.a_agency}",
    "{last_deeplink.a_my_adgroup}",
    "{last_deeplink.a_my_ad}",
    "{last_deeplink.a_my_campaign}",
    "{last_deeplink.a_adtouch_datetime}",
    "{last_deeplink.a_adtouch_timestamp}",
    "{last_deeplink.a_adtouch_timestamp_d}",
    "{last_deeplink.m_creative}",
    "{last_deeplink.m_publisher}",
    "{last_deeplink.m_sub_publisher}",
    "{last_deeplink.m_adgroup}",
    "{last_deeplink.m_ad}",
    "{last_deeplink.m_keyword}",
    "{last_deeplink.m_placement}",
    "{last_deeplink.m_cost_model}",
    "{last_deeplink.m_cost}",
    "{last_deeplink.m_cost_currency}",
    "{last_deeplink.m_play_percent}",
    "{last_deeplink.m_play_second}",
    "{last_deeplink.m_view_percent}",
    "{last_deeplink.m_view_second}",
    "{last_deeplink.cb_1}",
    "{last_deeplink.cb_2}",
    "{last_deeplink.cb_3}",
    "{last_deeplink.cb_4}",
    "{last_deeplink.cb_5}",
    "{last_deeplink.m_adid}",
    "{last_deeplink.utm_source}",
    "{last_deeplink.utm_medium}",
    "{last_deeplink.utm_campaign}",
    "{last_deeplink.utm_term}",
    "{last_deeplink.utm_content}",
    "{last_deeplink.adid}",
    "{last_deeplink.is_attr_owner}",
    "{last_deeplink.attr_model_flag}",
    "{last_deeplink.attr_model_str}",
    "{last_deeplink.i_request_type}",
    "{last_deeplink.attribute_datetime}",
    "{last_deeplink.attribute_timestamp}",
    "{last_deeplink.attribute_timestamp_d}",
    "{last_deeplink.seconds_gap}",
    "{last_deeplink.deeplink_custom_path}",
    "{last.a_key}",
    "{last.a_cookie}",
    "{last.a_ip}",
    "{last.a_fp}",
    "{last.a_country}",
    "{last.a_city}",
    "{last.a_region}",
    "{last.a_appkey}",
    "{last.a_partner}",
    "{last.a_agency}",
    "{last.a_my_adgroup}",
    "{last.a_my_ad}",
    "{last.a_my_campaign}",
    "{last.a_adtouch_datetime}",
    "{last.a_adtouch_timestamp}",
    "{last.a_adtouch_timestamp_d}",
    "{last.m_creative}",
    "{last.m_publisher}",
    "{last.m_sub_publisher}",
    "{last.m_adgroup}",
    "{last.m_ad}",
    "{last.m_keyword}",
    "{last.m_placement}",
    "{last.m_cost_model}",
    "{last.m_cost}",
    "{last.m_cost_currency}",
    "{last.m_play_percent}",
    "{last.m_play_second}",
    "{last.m_view_percent}",
    "{last.m_view_second}",
    "{last.cb_1}",
    "{last.cb_2}",
    "{last.cb_3}",
    "{last.cb_4}",
    "{last.cb_5}",
    "{last.m_adid}",
    "{last.utm_source}",
    "{last.utm_medium}",
    "{last.utm_campaign}",
    "{last.utm_term}",
    "{last.utm_content}",
    "{last.adid}",
    "{last.is_attr_owner}",
    "{last.attr_model_flag}",
    "{last.attr_model_str}",
    "{last.i_request_type}",
    "{last.attribute_datetime}",
    "{last.attribute_timestamp}",
    "{last.attribute_timestamp_d}",
    "{last.seconds_gap}",
    "{last.deeplink_custom_path}",
    "{req.common.identity.adid}",
    "{req.common.identity.idfv}",
    "{req.common.identity.ad_id_opt_out}",
    "{req.common.device_info.os}",
    "{req.common.device_info.model}",
    "{req.common.device_info.vendor}",
    "{req.common.device_info.resolution}",
    "{req.common.device_info.is_portrait}",
    "{req.common.device_info.platform}",
    "{req.common.device_info.network}",
    "{req.common.device_info.is_wifi_only}",
    "{req.common.device_info.carrier}",
    "{req.common.device_info.language}",
    "{req.common.device_info.country}",
    "{req.common.build_id}",
    "{req.common.package_name}",
    "{req.common.appkey}",
    "{req.common.sdk_version}",
    "{req.common.installer}",
    "{req.common.app_version}",
    "{req.evt.event_name}",
    "{req.evt.group}",
    "{req.evt.event_datetime}",
    "{req.evt.event_timestamp}",
    "{req.evt.event_timestamp_d}",
    "{req.evt.param_json}",
    "{req.evt.param.abx:order_id}",
    "{req.evt.param.abx:order_sales}",
    "{req.evt.param.abx:item.abx:product_id}",
    "{req.evt.param.abx:item.abx:product_name}",
    "{req.evt.param.abx:item.abx:price}",
    "{req.evt.param.abx:item.abx:qunatity}",
    "{req.evt.param.abx:item.abx:sales}",
    "{req.evt.param.abx:item.abx:discount}",
    "{req.evt.param.abx:item.abx:currency}",
    "{req.evt.param.abx:item.abx:category1}"
);
    $arrlength = count($macro);
    for ($x = 0; $x < $arrlength; $x++) {
        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
        }
        
    
            $sql = "INSERT INTO event_macro (event)
            VALUES ('$macro[$x]')";
        
        

        if ($conn->query($sql) === TRUE) {
        echo "New record created successfully";
        } else {
        echo "Error: " . $sql . "<br>" . $conn->error;
        }
    }



    $sql2 = "SELECT count(*) FROM event_macro";
    $result = $conn->query($sql2);

    if ($result->num_rows > 0) {
    // output data of each row
    while($row = $result->fetch_assoc()) {
        echo "  total count is  " .$row["count(*)"];
    }
    } else {
    echo "0 results";
    }
        $conn->close();
?>